site_name: Taccuino
site_description: Brief notes on Italian grammar and usage
site_url: https://dmpop.github.io/taccuino/
site_author: Dmitri Popov
repo_url: https://github.com/dmpop/taccuino/
edit_uri: blob/main/docs/
copyright: Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)
plugins:
  - search:
      lang:
        - en
        - it
  - git-revision-date-localized:
      type: date
  - awesome-pages
theme:
  name: material
  logo: logo.png
  favicon: logo.png
  features:
    - header.autohide
  palette:
    - scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Lato
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  consent:
    title: Yay, cookies!
    description: This site uses cookies. No, you can't eat them.
